//
//  SetupProfileVipInteractor.swift
//  IChatVIP
//
//  Created by Александр Бадмаев on 28.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FirebaseAuth

protocol SetupProfileVipBusinessLogic {
    func makeRequest(request: SetupProfileVip.Model.Request.RequestType)
}

protocol SetupProfileVipDataStore {
    var user: User? { get set }
    var muser: MUser? { get set }
}

class SetupProfileVipInteractor: SetupProfileVipBusinessLogic, SetupProfileVipDataStore {
    var presenter: SetupProfileVipPresentationLogic?
    var worker: SetupProfileVipWorker?
    
    var user: User?
    var muser: MUser?
    
    func makeRequest(request: SetupProfileVip.Model.Request.RequestType) {
        if worker == nil {
            worker = SetupProfileVipWorker()
        }
        
        switch request {
        case .setUsernameAndPhoto:
            presenter?.presentData(response: .presentUsernameAndPhoto(name: user?.displayName, photoUrl: user?.photoURL))
            
        case let .saveProfileWith(username, avatarImage, description, sex):
            if let user = user {
                FirestoreService.shared.saveProfileWith(
                    id: user.uid,
                    email: user.email!,
                    username: username,
                    avatarImage: avatarImage,
                    description: description,
                    sex: sex
                ) { (result) in
                    switch result {
                    case .success(let muser):
                        self.muser = muser
                        self.presenter?.presentData(response: .presentAlert(title: "Успешно", message: "Данные сохранены"))
                    case .failure(let error):
                        self.presenter?.presentData(response: .presentAlert(title: "Ошибка", message: error.localizedDescription))
                    }
                }
            }
        }
    }
    
}
