//
//  SetupProfileVipRouter.swift
//  IChatVIP
//
//  Created by Александр Бадмаев on 28.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetupProfileVipRoutingLogic {
    func showAlert(title: String, message: String, type: SetupProfileVip.AlertType)
    func routeToMainTabBar()
    func showImagePicker()
}

protocol SetupProfileVipDataPassing {
    var dataStore: SetupProfileVipDataStore? { get }
}

class SetupProfileVipRouter: NSObject, SetupProfileVipRoutingLogic, SetupProfileVipDataPassing {
    
    weak var viewController: SetupProfileVipViewController?
    var dataStore: SetupProfileVipDataStore?
    
    // MARK: Routing
    
    func showAlert(title: String, message: String, type: SetupProfileVip.AlertType) {
        let alertVC = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let okAction = UIAlertAction(title: "Ok", style: .default) { _ in
            switch type {
            case .profileSaved:
                self.routeToMainTabBar()
            case .other:
                break
            }
        }
        alertVC.addAction(okAction)
        presentFrom(source: viewController!, destination: alertVC)
    }
    
    func routeToMainTabBar() {
        let mainTabBarVC = MainTabBarViewController(currentUser: dataStore!.muser!)
        mainTabBarVC.modalPresentationStyle = .fullScreen
        presentFrom(source: viewController!, destination: mainTabBarVC)
    }
    
    func showImagePicker() {
        let imagePickerController = UIImagePickerController()
        imagePickerController.delegate = viewController
        imagePickerController.sourceType = .photoLibrary
        presentFrom(source: viewController!, destination: imagePickerController)
    }
    
    // MARK: Navigation
    
    private func presentFrom(source: UIViewController, destination: UIViewController) {
        source.present(destination, animated: true)
    }
}
