//
//  SetupProfileVipModels.swift
//  IChatVIP
//
//  Created by Александр Бадмаев on 28.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SetupProfileVip {
    
    enum AlertType {
        case profileSaved
        case other
    }
    
    enum Model {
        struct Request {
            enum RequestType {
                case setUsernameAndPhoto
                case saveProfileWith(username: String?, avatarImage: UIImage?, description: String?, sex: String?)
            }
        }
        
        struct Response {
            enum ResponseType {
                case presentUsernameAndPhoto(name: String?, photoUrl: URL?)
                case presentAlert(title: String, message: String, type: AlertType)
            }
        }
        
        struct ViewModel {
            enum ViewModelData {
                case displayUsernameAndPhoto(name: String?, photoUrl: URL?)
                case displayAlert(title: String, message: String, type: AlertType)
            }
        }
    }
}
