//
//  SetupProfileVipModels.swift
//  IChatVIP
//
//  Created by Александр Бадмаев on 28.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SetupProfileVip {
    // MARK: Use cases
    
    enum Model {
        struct Request {
            enum RequestType {
                case saveProfileWith(username: String?, avatarImageString: String?, description: String?, sex: String?)
            }
        }
        
        struct Response {
            enum ResponseType {
                case presentAlert(title: String, message: String)
            }
        }
        
        struct ViewModel {
            enum ViewModelData {
                case displayAlert(title: String, message: String)
            }
        }
    }
}
