//
//  SetupProfileVipPresenter.swift
//  IChatVIP
//
//  Created by Александр Бадмаев on 28.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetupProfileVipPresentationLogic {
    func presentData(response: SetupProfileVip.Model.Response.ResponseType)
}

class SetupProfileVipPresenter: SetupProfileVipPresentationLogic {
    weak var viewController: SetupProfileVipDisplayLogic?
    
    // MARK: Do something
    
    func presentData(response: SetupProfileVip.Model.Response.ResponseType) {
        switch response {
        case let .presentUsernameAndPhoto(name, photoUrl):
            viewController?.displayData(viewModel: .displayUsernameAndPhoto(name: name, photoUrl: photoUrl))
        case let .presentAlert(title, message):
            viewController?.displayData(viewModel: .displayAlert(title: title, message: message))
        }
    }
}
